/*
 * This file is generated by jOOQ.
 */
package com.kushtrimh.tomorr.dal;


import com.kushtrimh.tomorr.dal.tables.Album;
import com.kushtrimh.tomorr.dal.tables.AppUser;
import com.kushtrimh.tomorr.dal.tables.Artist;
import com.kushtrimh.tomorr.dal.tables.ArtistAlbum;
import com.kushtrimh.tomorr.dal.tables.ArtistAppUser;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.album</code>.
     */
    public final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.artist</code>.
     */
    public final Artist ARTIST = Artist.ARTIST;

    /**
     * The table <code>public.artist_album</code>.
     */
    public final ArtistAlbum ARTIST_ALBUM = ArtistAlbum.ARTIST_ALBUM;

    /**
     * The table <code>public.artist_app_user</code>.
     */
    public final ArtistAppUser ARTIST_APP_USER = ArtistAppUser.ARTIST_APP_USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Album.ALBUM,
            AppUser.APP_USER,
            Artist.ARTIST,
            ArtistAlbum.ARTIST_ALBUM,
            ArtistAppUser.ARTIST_APP_USER);
    }
}
