/*
 * This file is generated by jOOQ.
 */
package com.kushtrimh.tomorr.dal;


import com.kushtrimh.tomorr.dal.tables.Album;
import com.kushtrimh.tomorr.dal.tables.AppUser;
import com.kushtrimh.tomorr.dal.tables.Artist;
import com.kushtrimh.tomorr.dal.tables.ArtistAlbum;
import com.kushtrimh.tomorr.dal.tables.ArtistAppUser;
import com.kushtrimh.tomorr.dal.tables.QrtzBlobTriggers;
import com.kushtrimh.tomorr.dal.tables.QrtzCalendars;
import com.kushtrimh.tomorr.dal.tables.QrtzCronTriggers;
import com.kushtrimh.tomorr.dal.tables.QrtzFiredTriggers;
import com.kushtrimh.tomorr.dal.tables.QrtzJobDetails;
import com.kushtrimh.tomorr.dal.tables.QrtzLocks;
import com.kushtrimh.tomorr.dal.tables.QrtzPausedTriggerGrps;
import com.kushtrimh.tomorr.dal.tables.QrtzSchedulerState;
import com.kushtrimh.tomorr.dal.tables.QrtzSimpleTriggers;
import com.kushtrimh.tomorr.dal.tables.QrtzSimpropTriggers;
import com.kushtrimh.tomorr.dal.tables.QrtzTriggers;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.album</code>.
     */
    public final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.app_user</code>.
     */
    public final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.artist</code>.
     */
    public final Artist ARTIST = Artist.ARTIST;

    /**
     * The table <code>public.artist_album</code>.
     */
    public final ArtistAlbum ARTIST_ALBUM = ArtistAlbum.ARTIST_ALBUM;

    /**
     * The table <code>public.artist_app_user</code>.
     */
    public final ArtistAppUser ARTIST_APP_USER = ArtistAppUser.ARTIST_APP_USER;

    /**
     * The table <code>public.qrtz_blob_triggers</code>.
     */
    public final QrtzBlobTriggers QRTZ_BLOB_TRIGGERS = QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS;

    /**
     * The table <code>public.qrtz_calendars</code>.
     */
    public final QrtzCalendars QRTZ_CALENDARS = QrtzCalendars.QRTZ_CALENDARS;

    /**
     * The table <code>public.qrtz_cron_triggers</code>.
     */
    public final QrtzCronTriggers QRTZ_CRON_TRIGGERS = QrtzCronTriggers.QRTZ_CRON_TRIGGERS;

    /**
     * The table <code>public.qrtz_fired_triggers</code>.
     */
    public final QrtzFiredTriggers QRTZ_FIRED_TRIGGERS = QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS;

    /**
     * The table <code>public.qrtz_job_details</code>.
     */
    public final QrtzJobDetails QRTZ_JOB_DETAILS = QrtzJobDetails.QRTZ_JOB_DETAILS;

    /**
     * The table <code>public.qrtz_locks</code>.
     */
    public final QrtzLocks QRTZ_LOCKS = QrtzLocks.QRTZ_LOCKS;

    /**
     * The table <code>public.qrtz_paused_trigger_grps</code>.
     */
    public final QrtzPausedTriggerGrps QRTZ_PAUSED_TRIGGER_GRPS = QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS;

    /**
     * The table <code>public.qrtz_scheduler_state</code>.
     */
    public final QrtzSchedulerState QRTZ_SCHEDULER_STATE = QrtzSchedulerState.QRTZ_SCHEDULER_STATE;

    /**
     * The table <code>public.qrtz_simple_triggers</code>.
     */
    public final QrtzSimpleTriggers QRTZ_SIMPLE_TRIGGERS = QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS;

    /**
     * The table <code>public.qrtz_simprop_triggers</code>.
     */
    public final QrtzSimpropTriggers QRTZ_SIMPROP_TRIGGERS = QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS;

    /**
     * The table <code>public.qrtz_triggers</code>.
     */
    public final QrtzTriggers QRTZ_TRIGGERS = QrtzTriggers.QRTZ_TRIGGERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Album.ALBUM,
            AppUser.APP_USER,
            Artist.ARTIST,
            ArtistAlbum.ARTIST_ALBUM,
            ArtistAppUser.ARTIST_APP_USER,
            QrtzBlobTriggers.QRTZ_BLOB_TRIGGERS,
            QrtzCalendars.QRTZ_CALENDARS,
            QrtzCronTriggers.QRTZ_CRON_TRIGGERS,
            QrtzFiredTriggers.QRTZ_FIRED_TRIGGERS,
            QrtzJobDetails.QRTZ_JOB_DETAILS,
            QrtzLocks.QRTZ_LOCKS,
            QrtzPausedTriggerGrps.QRTZ_PAUSED_TRIGGER_GRPS,
            QrtzSchedulerState.QRTZ_SCHEDULER_STATE,
            QrtzSimpleTriggers.QRTZ_SIMPLE_TRIGGERS,
            QrtzSimpropTriggers.QRTZ_SIMPROP_TRIGGERS,
            QrtzTriggers.QRTZ_TRIGGERS);
    }
}
