/*
 * This file is generated by jOOQ.
 */
package com.kushtrimh.tomorr.dal;


import com.kushtrimh.tomorr.dal.tables.Album;
import com.kushtrimh.tomorr.dal.tables.AppUser;
import com.kushtrimh.tomorr.dal.tables.Artist;
import com.kushtrimh.tomorr.dal.tables.ArtistAlbum;
import com.kushtrimh.tomorr.dal.tables.ArtistAppUser;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.album</code>.
     */
    public static final Album ALBUM = Album.ALBUM;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.artist</code>.
     */
    public static final Artist ARTIST = Artist.ARTIST;

    /**
     * The table <code>public.artist_album</code>.
     */
    public static final ArtistAlbum ARTIST_ALBUM = ArtistAlbum.ARTIST_ALBUM;

    /**
     * The table <code>public.artist_app_user</code>.
     */
    public static final ArtistAppUser ARTIST_APP_USER = ArtistAppUser.ARTIST_APP_USER;
}
