version: 0.0
os: linux
files:
    - source: target/tomorr.jar
      destination: /tomorr.jar
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
  ApplicationStart:
    - location: scripts/start-server.sh