version: 0.0
os: linux
files:
    - source: target/
      destination: /usr/tmp/
hooks:
  ApplicationStop:
    - location: scripts/stop-server.sh
      runas: codedeployer
  ApplicationStart:
    - location: scripts/start-server.sh
      runas: codedeployer
  ValidateService:
    - location: scripts/validate-server.sh
      runas: codedeployer