version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/custom/jdk-16.0.1"

phases:
  install:
    commands:
      - echo Started installing dependenccies
      - echo Installing Java 16
      - wget https://download.java.net/java/GA/jdk16.0.1/7147401fd7354114ac51ef3e1328291f/9/GPL/openjdk-16.0.1_linux-x64_bin.tar.gz
      - mkdir /usr/lib/jvm/custom/
      - tar -xf openjdk-16.0.1_linux-x64_bin.tar.gz --directory /usr/lib/jvm/custom
      - echo Installing maven
      - yum -y install maven
      - echo Installing Docker
      - yum install -y http://docker-release-yellow-prod.s3-website-us-east-1.amazonaws.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.4.4-3.1.el8.x86_64.rpm
      - yum install -y http://docker-release-yellow-prod.s3-website-us-east-1.amazonaws.com/linux/centos/8/x86_64/stable/Packages/docker-ce-cli-20.10.6-3.el8.x86_64.rpm
      - yum install -y http://docker-release-yellow-prod.s3-website-us-east-1.amazonaws.com/linux/centos/8/x86_64/stable/Packages/docker-ce-20.10.6-3.el8.x86_64.rpm
  pre_build:
    commands:
      - echo Starting docker
      - systemctl start docker
  build:
    commands:
      - mvn package
