version: "3.8"

services:
  tomorr:
    image: kushtrimh/tomorr
    restart: always
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ${TOMORR_EXTERNAL_CONFIG}:/etc/tomorr/application.yml
    ports:
      - "8098:8098"
      - "5005:5005"
    depends_on:
      - postgres
      - redis
      - rabbitmq
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar ./tomorr.jar --spring.config.additional-location=optional:/etc/tomorr/application.yml
  postgres:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: tomorrpostgres
      POSTGRES_DB: tomorr
    volumes:
      - ./schema/init.sql:/docker-entrypoint-initdb.d/init.sql
      - database_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: redis:6.2.6
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3.9.11-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  database_data:
  redis_data:
  rabbitmq_data: