server:
  port: 8098
spring:
  application:
    name: tomorr
  messages:
    basename: messages/messages
  quartz:
    job-store-type: jdbc
    startup-delay: 15s
    properties:
      org:
        quartz:
          scheduler:
            instanceName: tomorr-scheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            useProperties: true
            tablePrefix: qrtz_
            misfireThreshold: 60000
            isClustered: true
            clusterCheckinInterval: 10000
datasource:
  url: ${TOMORR_DB_URL}
  username: ${TOMORR_DB_USERNAME}
  password: ${TOMORR_DB_PASSWORD}
spotify:
  client-id: ${TOMORR_SPOTIFY_CLIENT_ID}
  client-secret: ${TOMORR_SPOTIFY_CLIENT_SECRET}
  user-agent: tomorr/0.0.1
  auth-url: https://accounts.spotify.com/api/token
  api-url: https://api.spotify.com/v1
redis:
  host: ${TOMORR_REDIS_HOST}
  port: ${TOMORR_REDIS_PORT}
request-limit:
  spotify-sync: 600
  spotify-search: 150
logging:
  level:
    com:
      kushtrimh:
        tomorr:
          spotify:
            http: INFO